categories:
  - title: 'OS'
    label: 'os'
  - title: 'Build'
    label: 'build'
  - title: 'Raspberry Pi'
    label: 'board/raspberry'
  - title: 'Open Virtual Appliance'
    label: 'board/ova'
  - title: 'Intel-Nuc'
    label: 'board/intel-nuc'
template: |
  ## Changes

  $CHANGES
