categories:
  - title: 'Home Assistant Operating System'
    label: 'os'
  - title: 'Build System'
    label: 'build'
  - title: 'Raspberry Pi'
    label: 'board/raspberrypi'
  - title: 'Open Virtual Appliance'
    label: 'board/ova'
  - title: 'Intel NUC'
    label: 'board/intel-nuc'
  - title: 'Hardkernel ODROID'
    label: 'board/hardkernel'
  - title: 'ASUS Tinker'
    label: 'board/tinker'
template: |
  ## Changes

  $CHANGES
