categories:
  - title: 'HassOS Core'
    label: 'os'
  - title: 'Build'
    label: 'build'
  - title: 'Raspberry Pi'
    label: 'board/raspberrypi'
  - title: 'Open Virtual Appliance'
    label: 'board/ova'
  - title: 'Intel-Nuc'
    label: 'board/intel-nuc'
  - title: 'Hardkernel'
    label: 'board/hardkernel'
template: |
  ## Changes

  $CHANGES
