# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
    - dev
  tags:
    include:
    - '*'
    exclude:
    - untagged*
pr:
- dev

variables:
  - name: versionHadolint
    value: 'v1.16.3'
  - name: versionShellCheck
    value: 'v0.6.0'
  - group: docker

jobs:

- job: 'Hadolint'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker pull hadolint/hadolint:$(versionHadolint)
    displayName: 'Install Hadolint'
  - script: |
      sudo docker run --rm -i \
        -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
        hadolint/hadolint:$(versionHadolint) < Dockerfile
    displayName: 'Run Hadolint'


- job: 'ShellCheck'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker pull koalaman/shellcheck:$(versionShellCheck)
    displayName: 'Install ShellCheck'
  - script: |
      sudo docker run --rm -i \
        -v $(pwd):/mnt:ro koalaman/shellcheck:$(versionShellCheck) \
          scripts/*.sh \
          buildroot-external/scripts/*.sh \
          buildroot-external/board/**/*.sh \
          buildroot-external/rootfs-overlay/usr/sbin/* \
          buildroot-external/rootfs-overlay/usr/libexec/* \
          buildroot-external/rootfs-overlay/usr/lib/rauc/*
    displayName: 'Run ShellCheck'


- job: 'AzureContainer'
  condition: and(eq(variables['Build.SourceBranchName'], 'dev'), succeeded('ShellCheck'), succeeded('Hadolint'))
  dependsOn:
    - 'ShellCheck'
    - 'Hadolint'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - script: |
      set -e

      sudo docker build -t homeassistant/hassos-azure:latest .azure
      sudo docker push homeassistant/hassos-azure:latest
    displayName: 'Update Azure build container'


# condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags'), succeeded('ShellCheck'), succeeded('AzureContainer'))
- job: 'Release'
  condition: and(eq(variables['Build.SourceBranchName'], 'dev'), succeeded('ShellCheck'), succeeded('AzureContainer'))
  dependsOn:
    - 'ShellCheck'
    - 'AzureContainer'
  pool:
    vmImage: 'ubuntu-16.04'
  container: 'homeassistant/hassos-azure'
  strategy:
    maxParallel: 1
    matrix:
      OpenVirtualAppliance:
        board: 'ova'
  steps:
  - script: sudo dockerd -s vfs &> /dev/null &
    displayName: 'Start docker'
  - script: make $(board)
    displayName: 'Build $(board)'
