# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
    - dev
pr:
- dev

variables:
  - name: versionHadolint
    value: 'v1.16.3'
  - name: versionShellCheck
    value: 'v0.6.0'

jobs:

- job: 'Hadolint'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo docker pull hadolint/hadolint:$(versionHadolint)
    displayName: 'Install Hadolint'
  - script: |
      sudo docker run --rm -i \
        -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
        hadolint/hadolint:$(versionHadolint) < Dockerfile
    displayName: 'Run Hadolint'


- job: 'ShellCheck'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo docker pull koalaman/shellcheck:$(versionShellCheck)
    displayName: 'Install ShellCheck'
  - script: |
      sudo docker run --rm -i \
        -v $(pwd):/mnt:ro koalaman/shellcheck:$(versionShellCheck) \
          scripts/*.sh \
          buildroot-external/scripts/*.sh \
          buildroot-external/board/**/*.sh \
          buildroot-external/rootfs-overlay/usr/sbin/* \
          buildroot-external/rootfs-overlay/usr/libexec/* \
          buildroot-external/rootfs-overlay/usr/lib/rauc/*
    displayName: 'Run ShellCheck'
