# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
    - dev
  tags:
    include:
    - '*'
    exclude:
    - untagged*
pr:
- dev

variables:
  - name: versionHadolint
    value: 'v1.16.3'
  - name: versionShellCheck
    value: 'v0.6.0'

jobs:

- job: 'Hadolint'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker pull hadolint/hadolint:$(versionHadolint)
    displayName: 'Install Hadolint'
  - script: |
      sudo docker run --rm -i \
        -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
        hadolint/hadolint:$(versionHadolint) < Dockerfile
    displayName: 'Run Hadolint'


- job: 'ShellCheck'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker pull koalaman/shellcheck:$(versionShellCheck)
    displayName: 'Install ShellCheck'
  - script: |
      sudo docker run --rm -i \
        -v $(pwd):/mnt:ro koalaman/shellcheck:$(versionShellCheck) \
          scripts/*.sh \
          buildroot-external/scripts/*.sh \
          buildroot-external/board/**/*.sh \
          buildroot-external/rootfs-overlay/usr/sbin/* \
          buildroot-external/rootfs-overlay/usr/libexec/* \
          buildroot-external/rootfs-overlay/usr/lib/rauc/*
    displayName: 'Run ShellCheck'


# condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags'), succeeded('ShellCheck'))
- job: 'Release'
  condition: and(eq(variables['Build.SourceBranchName'], 'dev'), succeeded('ShellCheck'))
  timeoutInMinutes: 240
  dependsOn:
    - 'ShellCheck'
  pool:
    name: 'Buildroot'
  strategy:
    maxParallel: 1
    matrix:
      OpenVirtualAppliance:
        board: 'ova'
  steps:
  - script: sudo docker build -t hassos:builder .
    displayName: 'Build container for HassOS'
  - script: |
      sudo modprobe overlayfs

      sudo docker run --rm --privileged -v "$(pwd):/build" \
        -v "/mnt/build-cache/cache:/cache" \
        hassos:builder make $(board)
    displayName: 'Build $(board)'
